site_name: SIMCE Docs

theme:
  name: "material"


plugins:
  - mkdocstrings

nav:
  - Documentación Proyecto SIMCE: index.md
  - Manual de referencia generación de insumos: generar_insumos_img.md
  - Manual de referencia recorte de subpreguntas: proc_imgs.md