site_name: SIMCE Docs

theme:
  name: "material"


plugins:
  - mkdocstrings
  - autorefs
  - search

nav:
  - Documentación Proyecto SIMCE: index.md
  - 'Manuales de referencia':
    - 'Generación de insumos': 'generar_insumos_img.md'
    - 'Recorte de subpreguntas': 'proc_imgs.md'