site_name: SIMCE Docs

theme:
  features:
    - content.code.copy
    - content.code.select
    - content.code.annotate
  name: material
  palette: 

    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Cambiar a modo oscurso

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Cambiar a modo normal

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

plugins:
  - mkdocstrings
  - autorefs
  - search

nav:
  - Documentación Proyecto SIMCE: index.md
  - Tutorial de uso de scripts de procesamiento y predicción: tutorial.md
  - Tutorial archivos de configuración: script_configuracion.md 
  - Guía de outputs del proyecto: outputs.md
  - 'Manuales de referencia':
    - 'Generación de insumos': 'generar_insumos_img.md'
    - 'Procesamiento tabla dobles marcas': 'proc_tabla_99.md'
    - 'Recorte de subpreguntas': 'proc_imgs.md'
    - 'Procesamiento paralelizado': 'paralelizacion.md'
    - 'Predicción': 'predicciones.md'
    - 'Indicadores de tinta': 'indicadores_tinta.md'
    - 'Funciones transversales': 'utils.md'
